# This is a TOML file

title = "My Configuration"

items = [
        "foo",
        "bar",
        "baz"
]

[database]
host = "localhost"
port = 5432
username = "user"
password = "secret"

items = [
        "foo",
        "bar",
        "baz"
]
